
name: Create Issue From File Example Command
on:
  workflow_dispatch:
jobs:
  createIssues:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Project team01
      run: |
        project_number=$(gh api -X POST /repos/${{ github.repository }}/projects  -H "Accept: application/vnd.github.v3+json"  -f name="team01" --jq '.id')
        echo 'PROJECT_NUMBER='$project_number >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Columns on team01
      run: |
        gh api -X POST /projects/${PROJECT_NUMBER}/columns  -H "Accept: application/vnd.github.v3+json"  -f name="Todo" 
        gh api -X POST /projects/${PROJECT_NUMBER}/columns  -H "Accept: application/vnd.github.v3+json"  -f name="In Progress" 
        gh api -X POST /projects/${PROJECT_NUMBER}/columns  -H "Accept: application/vnd.github.v3+json"  -f name="In Review" 
        gh api -X POST /projects/${PROJECT_NUMBER}/columns  -H "Accept: application/vnd.github.v3+json"  -f name="Done" 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Issue 1 From File
      id: step1
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Customize Home Controller and Tests
        content-filepath: issues/issue92_changes_to_README.md
    - name: Add Issue 1 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step1.outputs.issue-number }}

    - name: Create Issue 2 From File
      id: step2
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Update README with correct information in place of TODO
        content-filepath: issues/issue90_customize_home_controller.md
    - name: Add Issue 2 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step2.outputs.issue-number }}

    - name: Create Issue 3 From File
      id: step3
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up zipcode controller and tests
        content-filepath: issues/issue66_zipcode_controller_and_tests.md
    - name: Add Issue 3 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step3.outputs.issue-number }}

    - name: Create Issue 4 From File
      id: step4
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up zipcode service and tests
        content-filepath: issues/issue62_zipcode_service_and_tests.md
    - name: Add Issue 4 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step4.outputs.issue-number }}

    - name: Create Issue 5 From File
      id: step5
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up university controller and tests
        content-filepath: issues/issue56_university_controller_and_tests.md
    - name: Add Issue 5 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step5.outputs.issue-number }}

    - name: Create Issue 6 From File
      id: step6
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up university service and tests
        content-filepath: issues/issue52_university_service_and_tests.md
    - name: Add Issue 6 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step6.outputs.issue-number }}

    - name: Create Issue 7 From File
      id: step7
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up tides controller and tests
        content-filepath: issues/issue46_tides_controller_and_tests.md
    - name: Add Issue 7 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step7.outputs.issue-number }}

    - name: Create Issue 8 From File
      id: step8
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up tides service and tests
        content-filepath: issues/issue42_tides_service_and_tests.md
    - name: Add Issue 8 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step8.outputs.issue-number }}

    - name: Create Issue 9 From File
      id: step9
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up reddit controller and tests
        content-filepath: issues/issue36_reddit_controller_and_tests.md
    - name: Add Issue 9 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step9.outputs.issue-number }}

    - name: Create Issue 10 From File
      id: step10
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up reddit service and tests
        content-filepath: issues/issue32_reddit_service_and_tests.md
    - name: Add Issue 10 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step10.outputs.issue-number }}

    - name: Create Issue 11 From File
      id: step11
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up public holiday controller and tests
        content-filepath: issues/issue26_holiday_controller_and_tests.md
    - name: Add Issue 11 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step11.outputs.issue-number }}

    - name: Create Issue 12 From File
      id: step12
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up public holiday service and tests
        content-filepath: issues/issue22_holiday_service_and_tests.md
    - name: Add Issue 12 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step12.outputs.issue-number }}

    - name: Create Issue 13 From File
      id: step13
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up location controller and tests
        content-filepath: issues/issue16_location_controller_and_tests.md
    - name: Add Issue 13 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step13.outputs.issue-number }}

    - name: Create Issue 14 From File
      id: step14
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up location service and tests
        content-filepath: issues/issue12_location_service_and_tests.md
    - name: Add Issue 14 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step14.outputs.issue-number }}

    - name: Create Issue 15 From File
      id: step15
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up codecov token and codecov badge.
        content-filepath: issues/issue02_codecov_token.md
    - name: Add Issue 15 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step15.outputs.issue-number }}

    - name: Create Issue 16 From File
      id: step16
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Set up a team deployments for prod and qa on Heroku
        content-filepath: issues/issue00_set_up_deployment_on_heroku.md
    - name: Add Issue 16 to Kanban board team01
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: team01
        column-name: Todo
        issue-number: ${{ steps.step16.outputs.issue-number }}
